
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopXeMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.Comment = new HashSet<Comment>();
            this.SanPham_DatHang = new HashSet<SanPham_DatHang>();
            this.AnhXe = new HashSet<AnhXe>();
        }

        public int ID { get; set; }
        [DisplayName("Tên Xe")]
        public string TenSanPham { get; set; }
        [DisplayName("Giá Bán")]
        public Nullable<decimal> GiaBan { get; set; }
        [DisplayName("Ngày Nhập")]
        public Nullable<System.DateTime> NgayNhap { get; set; }
        [DisplayName("Còn Hàng")]
        public Nullable<bool> ConHang { get; set; }
        [DisplayName("Số Lượng")]
        public Nullable<long> SoLuong { get; set; }
        [DisplayName("Bài Viết")]
        public string BaiViet { get; set; }
        [DisplayName("Loại Xe")]
        public Nullable<int> IDLoaiSP { get; set; }
        [DisplayName("Hãng Xe")]
        public Nullable<int> IdHangSX { get; set; }
        [DisplayName("Giảm Giá")]
        public Nullable<int> idGiamGia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual GiamGia GiamGia { get; set; }
        public virtual HangSX HangSX { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_DatHang> SanPham_DatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhXe> AnhXe { get; set; }
    }
}
