//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopXeMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.Comment = new HashSet<Comment>();
            this.DonHang = new HashSet<DonHang>();
        }
    
        public int Id { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        public string TenDangNhap { get; set; }
        [DisplayName("Mật Khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("Ngày Đăng Ký")]
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        [DisplayName("Tình Trạng")]
        public Nullable<bool> TinhTrang { get; set; }
        [DisplayName("Tên Người Dùng")]
        public string TenNguoiDung { get; set; }
        public Nullable<int> idPhanQuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        [DisplayName("Phân quyền")]
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
